//go:build !ignore_autogenerated

// +kubebuilder:object:generate=true

// +k8s:deepcopy-gen=package.

// Package v1 contains API Schema definitions for nephoran.io v1.

// Package v1 contains API Schema definitions for the Nephoran Intent Operator, providing
// comprehensive Kubernetes Custom Resource Definitions (CRDs) for telecommunications
// network orchestration. This package serves as the primary interface for defining
// and managing network functions, certificates, audit trails, disaster recovery,
// and other critical components in O-RAN and 5G network environments.
package v1

//go:generate controller-gen object paths=.
