//go:build !ignore_autogenerated



// +kubebuilder:object:generate=true.

// +k8s:deepcopy-gen=package.



// Package v1 contains API Schema definitions for nephoran.io v1.


package v1



//go:generate controller-gen object paths=.

