"""Gitea-backed GitOps automation (ADR-002, ADR-0002).

Workflow:
1. Clone or update the nephoran-packages repo from Gitea
2. Create a feature branch: intent/{intentId}
3. Copy generated kpt packages into the repo
4. Commit and push
5. Open a Pull Request via Gitea API

All mutations go through Git PRs — never direct kubectl apply (Hard Rule #1, #2).
"""
from __future__ import annotations

import json
import logging
import os
import shutil
from pathlib import Path
from typing import Any

import requests
from git import Repo
from urllib.parse import urlparse, urlunparse

logger = logging.getLogger(__name__)

GITEA_URL = os.getenv("GITEA_URL", "http://localhost:3000")
GITEA_TOKEN = os.getenv("GITEA_TOKEN", "")
GITEA_OWNER = os.getenv("GITEA_OWNER", "nephio")
GITEA_REPO = os.getenv("GITEA_REPO", "nephoran-packages")
GITEA_CLONE_URL = os.getenv(
    "GITEA_CLONE_URL",
    f"http://localhost:3000/{GITEA_OWNER}/{GITEA_REPO}.git",
)
WORK_DIR = Path(os.getenv("GITOPS_WORK_DIR", "/tmp/nephoran-gitops"))


def _auth_url(url: str, token: str) -> str:
    """Embed token into a git HTTP URL for push authentication.

    http://host/repo.git → http://oauth2:TOKEN@host/repo.git
    If token is empty or URL already has credentials, returns url unchanged.
    """
    if not token:
        return url
    parsed = urlparse(url)
    if parsed.username:
        return url  # already has credentials
    authed = parsed._replace(netloc=f"oauth2:{token}@{parsed.hostname}" +
                             (f":{parsed.port}" if parsed.port else ""))
    return urlunparse(authed)


def _ensure_repo() -> Repo:
    """Clone or pull the latest from Gitea."""
    repo_dir = WORK_DIR / GITEA_REPO
    clone_url = _auth_url(GITEA_CLONE_URL, GITEA_TOKEN)

    if repo_dir.exists() and (repo_dir / ".git").exists():
        repo = Repo(repo_dir)
        origin = repo.remotes.origin
        # Ensure remote URL has current auth token (token may change between runs)
        if origin.url != clone_url:
            origin.set_url(clone_url)
        # Discard ALL leftover state from previous pipeline runs:
        # 1. reset --hard unstages index AND restores working tree to HEAD
        # 2. clean -fd removes untracked files and directories
        # 3. checkout -f main forces branch switch even if on a detached HEAD
        repo.git.reset("--hard", "HEAD")
        repo.git.clean("-fd")
        repo.git.checkout("-f", "main")
        origin.pull()
        logger.info("Pulled latest from Gitea")
        return repo
    else:
        repo_dir.mkdir(parents=True, exist_ok=True)
        repo = Repo.clone_from(clone_url, repo_dir)
        logger.info("Cloned repo to %s", repo_dir)
        return repo


def _create_branch(repo: Repo, branch_name: str) -> None:
    """Create and checkout a new branch from main."""
    if branch_name in [ref.name for ref in repo.branches]:
        repo.git.checkout(branch_name)
        logger.info("Checked out existing branch %s", branch_name)
    else:
        repo.git.checkout("main")
        repo.git.checkout("-b", branch_name)
        logger.info("Created branch %s", branch_name)


def _copy_packages(repo: Repo, pkg_dir: Path, intent_id: str) -> list[str]:
    """Copy generated packages into the repo under packages/instances/{intentId}/."""
    repo_dir = Path(repo.working_dir)
    dest = repo_dir / "packages" / "instances" / intent_id
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(pkg_dir, dest)
    logger.info("Copied packages from %s to %s", pkg_dir, dest)

    # Return relative paths for staging
    return [str(p.relative_to(repo_dir)) for p in dest.rglob("*") if p.is_file()]


def _commit_and_push(repo: Repo, branch_name: str, intent_id: str, files: list[str]) -> str:
    """Stage files, commit, and push to origin."""
    for f in files:
        repo.index.add([f])

    message = f"feat(intent): add generated packages for {intent_id}\n\nGenerated by nephoran intentctl pipeline.\nIntent ID: {intent_id}"
    commit = repo.index.commit(message)
    logger.info("Committed %s (%s)", commit.hexsha[:8], message.split("\n")[0])

    repo.git.push("origin", branch_name, force=True)
    logger.info("Pushed branch %s to origin", branch_name)
    return commit.hexsha


def _open_pr(intent_id: str, branch_name: str, plan: dict[str, Any]) -> dict[str, Any] | None:
    """Open a Pull Request on Gitea via API."""
    if not GITEA_TOKEN:
        logger.warning("GITEA_TOKEN not set — skipping PR creation (dry-run mode)")
        return {"dry_run": True, "branch": branch_name, "intent_id": intent_id}

    api_url = f"{GITEA_URL}/api/v1/repos/{GITEA_OWNER}/{GITEA_REPO}/pulls"
    headers = {"Authorization": f"token {GITEA_TOKEN}", "Content-Type": "application/json"}

    actions_summary = ", ".join(
        f"{a['kind']} {a['component']}" + (f" (replicas={a['replicas']})" if 'replicas' in a else "")
        for a in plan.get("actions", [])
    )

    pr_data = {
        "title": f"[Intent] {intent_id}: {plan.get('intentType', 'unknown')}",
        "body": f"""## Intent Plan

- **Intent ID**: {intent_id}
- **Type**: {plan.get('intentType', 'unknown')}
- **Description**: {plan.get('description', 'N/A')}
- **Actions**: {actions_summary}
- **Human Review Required**: {plan.get('policy', {}).get('requireHumanReview', True)}

### Guardrails
- denyClusterScoped: {plan.get('policy', {}).get('guardrails', {}).get('denyClusterScoped', True)}
- denyPrivileged: {plan.get('policy', {}).get('guardrails', {}).get('denyPrivileged', True)}
- denyHostNetwork: {plan.get('policy', {}).get('guardrails', {}).get('denyHostNetwork', True)}

### Generated Files
```json
{json.dumps(plan.get('actions', []), indent=2)}
```
""",
        "head": branch_name,
        "base": "main",
    }

    try:
        resp = requests.post(api_url, headers=headers, json=pr_data, timeout=30)
        if resp.status_code == 409:
            logger.info("PR already exists for branch %s — updating existing PR", branch_name)
            return {"existing": True, "branch": branch_name, "message": "PR already open for this branch"}
        resp.raise_for_status()
        pr = resp.json()
        logger.info("Created PR #%s: %s", pr.get("number"), pr.get("html_url"))
        return pr
    except requests.RequestException:
        logger.exception("Failed to create PR on Gitea")
        return None


def push_to_gitops(pkg_dir: Path, plan: dict[str, Any]) -> dict[str, Any]:
    """Full GitOps workflow: clone → branch → copy → commit → push → PR.

    Args:
        pkg_dir: Path to generated kpt packages directory.
        plan: The IntentPlan dict (for PR body content).

    Returns:
        Dict with branch, commit_sha, and pr_url (or dry_run info).
    """
    intent_id = plan["intentId"]
    branch_name = f"intent/{intent_id}"

    repo = _ensure_repo()
    _create_branch(repo, branch_name)
    files = _copy_packages(repo, pkg_dir, intent_id)
    commit_sha = _commit_and_push(repo, branch_name, intent_id, files)
    pr = _open_pr(intent_id, branch_name, plan)

    return {
        "intent_id": intent_id,
        "branch": branch_name,
        "commit_sha": commit_sha,
        "pr": pr,
        "files_count": len(files),
    }
