apiVersion: v1
kind: Service
metadata:
  name: oai-odu
  namespace: oran
  labels:
    app.kubernetes.io/name: oai-odu
    app.kubernetes.io/managed-by: nephio
    app.kubernetes.io/part-of: llm-nephio-oran
    oran.ai/component: oai-odu
spec:
  selector:
    app.kubernetes.io/name: oai-odu
  ports:
  - port: 38472
    targetPort: 38472
    protocol: SCTP
