//go:build !ignore_autogenerated

package v1alpha1

// This file was previously used for manual deepcopy implementations
// but has been removed to avoid conflicts with auto-generated code.
// All deepcopy methods are now handled by controller-gen in zz_generated.deepcopy.go
