//go:build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkIntent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}