//go:build !ignore_autogenerated

// +kubebuilder:object:generate=true.
// +k8s:deepcopy-gen=package.

// Package v1alpha1 contains API Schema definitions for intent.nephoran.io v1alpha1.
// This package defines the NetworkIntent CRD and related types for managing network intents
// within the Nephoran Intent Operator.
package v1alpha1

//go:generate controller-gen object paths=.
