//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkIntent) DeepCopyInto(out *NetworkIntent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkIntent.
func (in *NetworkIntent) DeepCopy() *NetworkIntent {
	if in == nil {
		return nil
	}
	out := new(NetworkIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkIntentDefaulter) DeepCopyInto(out *NetworkIntentDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkIntentDefaulter.
func (in *NetworkIntentDefaulter) DeepCopy() *NetworkIntentDefaulter {
	if in == nil {
		return nil
	}
	out := new(NetworkIntentDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkIntentList) DeepCopyInto(out *NetworkIntentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkIntent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkIntentList.
func (in *NetworkIntentList) DeepCopy() *NetworkIntentList {
	if in == nil {
		return nil
	}
	out := new(NetworkIntentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkIntentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkIntentSpec) DeepCopyInto(out *NetworkIntentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkIntentSpec.
func (in *NetworkIntentSpec) DeepCopy() *NetworkIntentSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkIntentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkIntentStatus) DeepCopyInto(out *NetworkIntentStatus) {
	*out = *in
	if in.ObservedReplicas != nil {
		in, out := &in.ObservedReplicas, &out.ObservedReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LLMResponse != nil {
		in, out := &in.LLMResponse, &out.LLMResponse
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkIntentStatus.
func (in *NetworkIntentStatus) DeepCopy() *NetworkIntentStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkIntentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkIntentValidator) DeepCopyInto(out *NetworkIntentValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkIntentValidator.
func (in *NetworkIntentValidator) DeepCopy() *NetworkIntentValidator {
	if in == nil {
		return nil
	}
	out := new(NetworkIntentValidator)
	in.DeepCopyInto(out)
	return out
}
