apiVersion: v1
kind: Service
metadata:
  name: oai-cu-cp
  namespace: oran
  labels:
    app.kubernetes.io/name: oai-cu-cp
    app.kubernetes.io/managed-by: nephio
    app.kubernetes.io/part-of: llm-nephio-oran
    oran.ai/component: oai-cu-cp
spec:
  selector:
    app.kubernetes.io/name: oai-cu-cp
  ports:
  - port: 38472
    targetPort: 38472
    protocol: SCTP
