apiVersion: v1
kind: Service
metadata:
  name: oai-cu-up
  namespace: oran
  labels:
    app.kubernetes.io/name: oai-cu-up
    app.kubernetes.io/managed-by: nephio
    app.kubernetes.io/part-of: llm-nephio-oran
    oran.ai/component: oai-cu-up
spec:
  selector:
    app.kubernetes.io/name: oai-cu-up
  ports:
  - port: 2152
    targetPort: 2152
    protocol: UDP
