---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-xapp
  namespace: ricxapp
  labels:
    app: scaling-xapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-xapp
  template:
    metadata:
      labels:
        app: scaling-xapp
    spec:
      serviceAccountName: scaling-xapp-sa
      containers:
      - name: scaling-xapp
        image: busybox:latest
        command: ["/bin/sh", "-c", "sleep 3600"]
        env:
        - name: A1_MEDIATOR_URL
          value: "http://service-ricplt-a1mediator-http.ricplt.svc.cluster.local:10000"
        - name: REDIS_ADDRESS
          value: "a1-status-store.ricplt:6379"
        ports:
        - containerPort: 2112
          name: metrics
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
