apiVersion: v1
kind: Service
metadata:
  name: sim-e2
  namespace: sim
  labels:
    app.kubernetes.io/name: sim-e2
    app.kubernetes.io/managed-by: nephio
    app.kubernetes.io/part-of: llm-nephio-oran
    oran.ai/component: sim-e2
spec:
  selector:
    app.kubernetes.io/name: sim-e2
  ports:
  - port: 36421
    targetPort: 36421
    protocol: SCTP
